// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecommendSystem.Repositories;

namespace RecommendSystem.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201218085426_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RecommendSystem.Models.Item", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("RecommendSystem.Models.ItemReview", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReviewId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ItemId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("ItemReview");
                });

            modelBuilder.Entity("RecommendSystem.Models.Review", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Stars")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("RecommendSystem.Models.ItemReview", b =>
                {
                    b.HasOne("RecommendSystem.Models.Item", "Item")
                        .WithMany("ItemReviews")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RecommendSystem.Models.Review", "Review")
                        .WithMany("ItemReviews")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("RecommendSystem.Models.Item", b =>
                {
                    b.Navigation("ItemReviews");
                });

            modelBuilder.Entity("RecommendSystem.Models.Review", b =>
                {
                    b.Navigation("ItemReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
